/**
 * Writes a minimal, valid text PDF (Helvetica, one text object per line). Deterministic output: used for unit tests
 * and to generate benchmark fixtures, so the fixture provenance is "generated by this repository".
 */
export interface PdfLine {
  text: string;
  size?: number;
}

export function makePdf(pages: PdfLine[][], title: string): Buffer {
  const esc = (s: string) => s.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
  const objects: string[] = [];
  const pageIds: number[] = [];
  // 1: catalog, 2: pages, 3: font, 4: info; pages start at 5
  let next = 5;
  const pageObjs: { id: number; content: number; stream: string }[] = [];
  for (const lines of pages) {
    let y = 760;
    const ops: string[] = [];
    for (const line of lines) {
      const size = line.size ?? 11;
      if (line.text === "") {
        y -= size * 1.2;
        continue;
      }
      ops.push(`BT /F1 ${size} Tf 72 ${y.toFixed(1)} Td (${esc(line.text)}) Tj ET`);
      y -= size * 1.35;
    }
    const stream = ops.join("\n");
    pageObjs.push({ id: next, content: next + 1, stream });
    pageIds.push(next);
    next += 2;
  }
  objects[1] = "<< /Type /Catalog /Pages 2 0 R >>";
  objects[2] = `<< /Type /Pages /Kids [${pageIds.map((i) => `${i} 0 R`).join(" ")}] /Count ${pageIds.length} >>`;
  objects[3] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>";
  objects[4] = `<< /Title (${esc(title)}) /Producer (fetchkeep test support) >>`;
  for (const p of pageObjs) {
    objects[p.id] = `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents ${p.content} 0 R >>`;
    objects[p.content] = `<< /Length ${Buffer.byteLength(p.stream, "latin1")} >>\nstream\n${p.stream}\nendstream`;
  }
  let out = "%PDF-1.4\n";
  const offsets: number[] = [];
  for (let i = 1; i < objects.length; i++) {
    offsets[i] = Buffer.byteLength(out, "latin1");
    out += `${i} 0 obj\n${objects[i]}\nendobj\n`;
  }
  const xref = Buffer.byteLength(out, "latin1");
  out += `xref\n0 ${objects.length}\n0000000000 65535 f \n`;
  for (let i = 1; i < objects.length; i++) out += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  out += `trailer\n<< /Size ${objects.length} /Root 1 0 R /Info 4 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
  return Buffer.from(out, "latin1");
}
