#!/usr/bin/env node
// Regenerates THIRD_PARTY_LICENSES.md from the installed production dependency tree.
// Usage: npm run licenses [-- --check]
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const root = new URL("..", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");
const npmCli = process.env.npm_execpath;
if (!npmCli) {
  console.error("run via `npm run licenses`");
  process.exit(1);
}
const tree = JSON.parse(
  execFileSync(process.execPath, [npmCli, "ls", "--omit=dev", "--omit=peer", "--all", "--json", "--long"], {
    cwd: root,
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
  }),
);

const seen = new Map();
function walk(deps) {
  for (const [name, info] of Object.entries(deps ?? {})) {
    if (!info.version || !info.path) continue;
    const key = `${name}@${info.version}`;
    if (seen.has(key)) continue;
    let license = "UNKNOWN";
    let repo = "";
    const pj = join(info.path, "package.json");
    if (existsSync(pj)) {
      const pkg = JSON.parse(readFileSync(pj, "utf8"));
      license = typeof pkg.license === "string" ? pkg.license : pkg.license?.type ?? "UNKNOWN";
      repo = typeof pkg.repository === "string" ? pkg.repository : pkg.repository?.url ?? "";
      repo = repo.replace(/^git\+/, "").replace(/\.git$/, "").replace(/^git:\/\//, "https://");
    }
    seen.set(key, { name, version: info.version, license, repo, optional: Boolean(info.optional) });
    walk(info.dependencies);
  }
}
walk(tree.dependencies);

const rows = [...seen.values()].sort((a, b) => a.name.localeCompare(b.name));
const header = `# Third-party licenses

Fetchkeep is licensed under Apache-2.0. It does not vendor third-party source code. The npm package depends on
the packages below, which are installed from the npm registry under their own licenses. Each package's license
text ships inside its own directory in \`node_modules\`.

This file is generated by \`node scripts/licenses.mjs\`; do not edit the table by hand.

## Runtime dependencies (installed by default)

| Package | Version | License | Source |
|---|---|---|---|
`;
const table = rows
  .map((r) => `| \`${r.name}\`${r.optional ? " (optional)" : ""} | ${r.version} | ${r.license} | ${r.repo} |`)
  .join("\n");

const manual = readFileSync(join(root, "scripts", "licenses-extra.md"), "utf8");
const out = `${header}${table}\n\n${manual}`;
const target = join(root, "THIRD_PARTY_LICENSES.md");
if (process.argv.includes("--check")) {
  const current = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (current.replace(/\r\n/g, "\n") !== out) {
    console.error("THIRD_PARTY_LICENSES.md is out of date; run node scripts/licenses.mjs");
    process.exit(1);
  }
} else {
  writeFileSync(target, out);
  console.error(`wrote ${rows.length} packages`);
}
const bad = rows.filter((r) => /GPL|AGPL|SSPL|UNKNOWN/i.test(r.license) && !/LGPL/i.test(r.license));
if (bad.length) {
  console.error("Copyleft or unknown licenses in runtime tree:", bad.map((r) => `${r.name} ${r.license}`).join(", "));
  process.exit(2);
}
